In [1]:
# In class exercise 1: Basic Array Creation
# Create a NumPy array of 10 integers starting from 5 and ending at 50 (inclusive) with equal intervals. You can use the np.linspace built in method. 

# Expected Output:

# array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

import numpy as np

array = np.linspace(5, 50, 10, dtype=int) #linspaceとは、指定した範囲内で、指定した数の等間隔な数値を返す関数
print(array)

[ 5 10 15 20 25 30 35 40 45 50]


In [3]:
# In class exercise 2: Array Reshaping
# Given the following NumPy array:

# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
# Reshape it into a 3x4 matrix.

# Expected Output:

# array([[ 1, 2, 3, 4], 
#        [ 5, 6, 7, 8], 
#        [ 9, 10, 11, 12]])

import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped_array = array.reshape(3, 4)

print(reshaped_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
# In class exercise 3: Array Indexing
# Given the following 2D NumPy array:

# arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Extract the middle row and the middle element of that row.

# Expected Output:

# Middle row: [4, 5, 6] 
# Middle element of the middle row: 5

import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
middle_row = array_2d[1]
middle_element = array_2d[1][1]

print("Middle row:", middle_row)
print("Middle element of the middle row:", middle_element)

Middle row: [4 5 6]
Middle element of the middle row: 5


In [6]:
# In class exercise 4: Basic Array Operations
# Create two NumPy arrays a and b:

# a = np.array([1, 2, 3]) 
# b = np.array([4, 5, 6])
# Compute the dot product of a and b.

# Expected Output:

# 32

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_product = np.dot(a, b) # dot product = 内積

print(dot_product)

32


In [20]:
# In class exercise 5: Array Filtering
# Given the following NumPy array:

# arr = np.array([10, 25, 30, 45, 50, 65, 70, 85, 90, 105])
# Create a new array that only contains values greater than 50 and less than 100.

# Expected Output:

# array([65, 70, 85, 90])

import numpy as np

arr = np.array([10, 25, 30, 45, 50, 65, 70, 85, 90, 105])
new_arr = arr[(arr > 50) & (arr < 100)]

print(f"array{new_arr}")

array[65 70 85 90]


In [13]:
# In class exercise 6: Zeroes and Ones
# Create a 3x3 NumPy array filled with zeroes, and another 2x2 NumPy array filled with ones.

import numpy as np

zero_array = np.zeros((3, 3)) #zeros = 0で埋める
one_array = np.ones((2, 2)) # ones = 1で埋める

print(zero_array)
print(one_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]


In [14]:
# In class exercise 7: Diagonal Array
# Create a 4x4 identity matrix (a square matrix in which all the elements of the principal diagonal are ones, and all other elements are zeros).

import numpy as np

identity_matrix = np.eye(4) #eye = 単位行列を作る
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
# In class exercise 8: Element-wise Multiplication
# Given two arrays:

# a = np.array([[1, 2], [3, 4]]) 
# b = np.array([[5, 6], [7, 8]])
# Multiply them element-wise.

# Hint: To multiply the two given arrays element-wise, you simply use the * operator. This will perform element-by-element multiplication rather than matrix multiplication (which is done with np.dot() or the @ operator in Python).

# Complication: Do the element-wise multiplication using for loops.

# However, it's important to note that using explicit loops in Python, especially with NumPy arrays, is often slower than using built-in vectorized operations.
# The beauty of NumPy lies in its ability to perform operations on entire arrays at once without the need for explicit loops.
# The loop-based method is mainly for understanding and is not recommended for large datasets or performance-sensitive tasks.

# ---NumPy's Built-in Capabilities---

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

element_wise_multiplication = a * b

print(element_wise_multiplication)

# ---Using for loops---

import numpy as np

rows, cols = a.shape
result_loop = np.zeros((rows, cols))

for i in range(rows):
    for j in range(cols):
        result_loop[i][j] = a[i][j] * b[i][j]

print(result_loop)

[[ 5 12]
 [21 32]]
[[ 5. 12.]
 [21. 32.]]


In [18]:
# In class exercise 9: Array Transposition
# Given the following array:

# arr = np.array([[1, 2, 3],
#                 [4, 5, 6]])
# Transpose the array.

import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6]])
transposed_array = array.T #T = 転置行列

print(transposed_array)

[[1 4]
 [2 5]
 [3 6]]
